name: Run transfer script on push

on:
  push:
    branches:
      - master

jobs:
  run-transfer-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "REPO_NAME=${{ secrets.REPO_NAME }}" >> .env
          echo "REPO_OWNER=${{ secrets.REPO_OWNER }}" >> .env

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run transfer script
        run: |
          chmod +x ./transfer.sh
          CLOUD=${{ secrets.CLOUD }} bash ./transfer.sh
