name: Run transfer script daily

on:
  schedule:
    - cron: '26 12 * * *'

jobs:
  run-transfer-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run transfer script
        run: |
          chmod +x ./transfer.sh
          bash ./transfer.sh
