name: Deploy on Discussion Create

on:
  discussion:
    types: [created, edited]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy webhook
        run: |
          curl -X POST ${{ secrets.DEPLOY_HOOK }}
